ITEM.name = "Cartão Level 3"
ITEM.description = "Um cartão simples de plástico, feito para manter segurança em certos níveis da base."
ITEM.model = "models/gibs/metal_gib4.mdl"
ITEM.class = "keycard_testclearance level #3"
ITEM.weaponCategory = "cart"
ITEM.category = "Cartões"
ITEM.price = 0
ITEM.width = 1
ITEM.height = 1
