ITEM.name = "Binocolos De Morteiro"
ITEM.description = "Um binocolos feito para auxiliar a eficiência de acertos de morteiros em combate."
ITEM.model = "models/niksacokica/tech/tech_camera.mdl"
ITEM.class = "mortar_range_finder"
ITEM.weaponCategory = "equip"
ITEM.category = "Equipamentos"
ITEM.price = 0
ITEM.width = 1
ITEM.height = 1
