ITEM.name = "Westar-35 Dupla do Jasper"
ITEM.description = "Um par de pistolas baseadas no modelo padrão da Westar-35, pessoalmente modificada pessoalmente por Jasper."
ITEM.model = "models/jajoff/sps/cgiweapons/tc13j/westarm35_pistol.mdl"
ITEM.skin = 3
ITEM.class = "sw_jasper_dual_westar35s"
ITEM.weaponCategory = "secondary"
ITEM.price = 0
ITEM.width = 2
ITEM.height = 2